name: macro-spain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas
      - plotly
      - streamlit
      - requests
      - jupyter
      - notebook
